package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.Generative_input;
/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Generative_input
 *
 * @version generated on Mon Jun 27 12:29:13 CEST 2011
 */
public class DefaultGenerative_input extends DefaultInput
         implements Generative_input {

    public DefaultGenerative_input(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultGenerative_input() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf

    public Object getIsInputInstanceOf() {
        return (Object) getPropertyValue(getIsInputInstanceOfProperty());
    }


    public RDFProperty getIsInputInstanceOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsInputInstanceOf() {
        return getPropertyValueCount(getIsInputInstanceOfProperty()) > 0;
    }


    public void setIsInputInstanceOf(Object newIsInputInstanceOf) {
        setPropertyValue(getIsInputInstanceOfProperty(), newIsInputInstanceOf);
    }
}
