package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Finding_input
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public class DefaultFinding_input extends DefaultInput
         implements Finding_input {

    public DefaultFinding_input(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultFinding_input() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf

    public Finding_res getIsInputInstanceOf() {
        return (Finding_res) getPropertyValueAs(getIsInputInstanceOfProperty(), Finding_res.class);
    }


    public RDFProperty getIsInputInstanceOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsInputInstanceOf() {
        return getPropertyValueCount(getIsInputInstanceOfProperty()) > 0;
    }


    public void setIsInputInstanceOf(Finding_res newIsInputInstanceOf) {
        setPropertyValue(getIsInputInstanceOfProperty(), newIsInputInstanceOf);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isInputNodeIn

    public Set getIsInputNodeIn() {
        return new HashSet(getPropertyValuesAs(getIsInputNodeInProperty(), Finding_MFrag.class));
    }


    public RDFProperty getIsInputNodeInProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isInputNodeIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsInputNodeIn() {
        return getPropertyValueCount(getIsInputNodeInProperty()) > 0;
    }


    public Iterator listIsInputNodeIn() {
        return listPropertyValuesAs(getIsInputNodeInProperty(), Finding_MFrag.class);
    }


    public void addIsInputNodeIn(Finding_MFrag newIsInputNodeIn) {
        addPropertyValue(getIsInputNodeInProperty(), newIsInputNodeIn);
    }


    public void removeIsInputNodeIn(Finding_MFrag oldIsInputNodeIn) {
        removePropertyValue(getIsInputNodeInProperty(), oldIsInputNodeIn);
    }


    public void setIsInputNodeIn(Set newIsInputNodeIn) {
        setPropertyValues(getIsInputNodeInProperty(), newIsInputNodeIn);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isParentOf

//    public Finding_res getIsParentOf() {
//        return (Finding_res) getPropertyValueAs(getIsParentOfProperty(), Finding_res.class);
//    }
    public Set getIsParentOf() {
        return (Set) getPropertyValueAs(getIsParentOfProperty(), Finding_res.class);
    }

    public RDFProperty getIsParentOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isParentOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsParentOf() {
        return getPropertyValueCount(getIsParentOfProperty()) > 0;
    }


    public void setIsParentOf(Finding_res newIsParentOf) {
        setPropertyValue(getIsParentOfProperty(), newIsParentOf);
    }
}
