package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.Hypothesis;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Hypothesis
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultHypothesis extends AbstractCodeGeneratorIndividual
         implements Hypothesis {

    public DefaultHypothesis(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultHypothesis() {
    }



    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis

    public Set getHasBayesianHypothesis() {
        return new HashSet(getPropertyValuesAs(getHasBayesianHypothesisProperty(), HypothesisNode.class));
    }


    public RDFProperty getHasBayesianHypothesisProperty() {
        final String uri = "http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasBayesianHypothesis() {
        return getPropertyValueCount(getHasBayesianHypothesisProperty()) > 0;
    }


    public Iterator listHasBayesianHypothesis() {
        return listPropertyValuesAs(getHasBayesianHypothesisProperty(), HypothesisNode.class);
    }


    public void addHasBayesianHypothesis(HypothesisNode newHasBayesianHypothesis) {
        addPropertyValue(getHasBayesianHypothesisProperty(), newHasBayesianHypothesis);
    }


    public void removeHasBayesianHypothesis(HypothesisNode oldHasBayesianHypothesis) {
        removePropertyValue(getHasBayesianHypothesisProperty(), oldHasBayesianHypothesis);
    }


    public void setHasBayesianHypothesis(Set newHasBayesianHypothesis) {
        setPropertyValues(getHasBayesianHypothesisProperty(), newHasBayesianHypothesis);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence

    public float getHypothesisConfidence() {
        return getPropertyValueLiteral(getHypothesisConfidenceProperty()).getFloat();
    }


    public RDFProperty getHypothesisConfidenceProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHypothesisConfidence() {
        return getPropertyValueCount(getHypothesisConfidenceProperty()) > 0;
    }


    public void setHypothesisConfidence(float newHypothesisConfidence) {
        setPropertyValue(getHypothesisConfidenceProperty(), new java.lang.Float(newHypothesisConfidence));
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure

    public Failure getRepresentsPossibleFailure() {
        return (Failure) getPropertyValueAs(getRepresentsPossibleFailureProperty(), Failure.class);
    }


    public RDFProperty getRepresentsPossibleFailureProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRepresentsPossibleFailure() {
        return getPropertyValueCount(getRepresentsPossibleFailureProperty()) > 0;
    }


    public void setRepresentsPossibleFailure(Failure newRepresentsPossibleFailure) {
        setPropertyValue(getRepresentsPossibleFailureProperty(), newRepresentsPossibleFailure);
    }
}
