package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.Exemplar;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Exemplar
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultExemplar extends AbstractCodeGeneratorIndividual
         implements Exemplar {

    public DefaultExemplar(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultExemplar() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isArgTermIn

    public Set getIsArgTermIn() {
        return new HashSet(getPropertyValuesAs(getIsArgTermInProperty(), ArgRelationship.class));
    }


    public RDFProperty getIsArgTermInProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isArgTermIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsArgTermIn() {
        return getPropertyValueCount(getIsArgTermInProperty()) > 0;
    }


    public Iterator listIsArgTermIn() {
        return listPropertyValuesAs(getIsArgTermInProperty(), ArgRelationship.class);
    }


    public void addIsArgTermIn(ArgRelationship newIsArgTermIn) {
        addPropertyValue(getIsArgTermInProperty(), newIsArgTermIn);
    }


    public void removeIsArgTermIn(ArgRelationship oldIsArgTermIn) {
        removePropertyValue(getIsArgTermInProperty(), oldIsArgTermIn);
    }


    public void setIsArgTermIn(Set newIsArgTermIn) {
        setPropertyValues(getIsArgTermInProperty(), newIsArgTermIn);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isExemplarIn

    public Set getIsExemplarIn() {
        return new HashSet(getPropertyValuesAs(getIsExemplarInProperty(), MFrag.class));
    }


    public RDFProperty getIsExemplarInProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isExemplarIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsExemplarIn() {
        return getPropertyValueCount(getIsExemplarInProperty()) > 0;
    }


    public Iterator listIsExemplarIn() {
        return listPropertyValuesAs(getIsExemplarInProperty(), MFrag.class);
    }


    public void addIsExemplarIn(MFrag newIsExemplarIn) {
        addPropertyValue(getIsExemplarInProperty(), newIsExemplarIn);
    }


    public void removeIsExemplarIn(MFrag oldIsExemplarIn) {
        removePropertyValue(getIsExemplarInProperty(), oldIsExemplarIn);
    }


    public void setIsExemplarIn(Set newIsExemplarIn) {
        setPropertyValues(getIsExemplarInProperty(), newIsExemplarIn);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#representsOVar

    public OVariable getRepresentsOVar() {
        return (OVariable) getPropertyValueAs(getRepresentsOVarProperty(), OVariable.class);
    }


    public RDFProperty getRepresentsOVarProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#representsOVar";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRepresentsOVar() {
        return getPropertyValueCount(getRepresentsOVarProperty()) > 0;
    }


    public void setRepresentsOVar(OVariable newRepresentsOVar) {
        setPropertyValue(getRepresentsOVarProperty(), newRepresentsOVar);
    }
}
