package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.ProbAssign;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ProbAssign
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public class DefaultProbAssign extends AbstractCodeGeneratorIndividual
         implements ProbAssign {

    public DefaultProbAssign(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultProbAssign() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasConditionant

    public Set getHasConditionant() {
        return new HashSet(getPropertyValuesAs(getHasConditionantProperty(), CondRelationship.class));
    }


    public RDFProperty getHasConditionantProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasConditionant";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasConditionant() {
        return getPropertyValueCount(getHasConditionantProperty()) > 0;
    }


    public Iterator listHasConditionant() {
        return listPropertyValuesAs(getHasConditionantProperty(), CondRelationship.class);
    }


    public void addHasConditionant(CondRelationship newHasConditionant) {
        addPropertyValue(getHasConditionantProperty(), newHasConditionant);
    }


    public void removeHasConditionant(CondRelationship oldHasConditionant) {
        removePropertyValue(getHasConditionantProperty(), oldHasConditionant);
    }


    public void setHasConditionant(Set newHasConditionant) {
        setPropertyValues(getHasConditionantProperty(), newHasConditionant);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasStateName

    public Entity getHasStateName() {
        return (Entity) getPropertyValueAs(getHasStateNameProperty(), Entity.class);
    }


    public RDFProperty getHasStateNameProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasStateName";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasStateName() {
        return getPropertyValueCount(getHasStateNameProperty()) > 0;
    }


    public void setHasStateName(Entity newHasStateName) {
        setPropertyValue(getHasStateNameProperty(), newHasStateName);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasStateProb

    public RDFSLiteral getHasStateProb() {
        return (RDFSLiteral) getPropertyValue(getHasStateProbProperty());
    }


    public RDFProperty getHasStateProbProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasStateProb";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasStateProb() {
        return getPropertyValueCount(getHasStateProbProperty()) > 0;
    }


    public void setHasStateProb(RDFSLiteral newHasStateProb) {
        setPropertyValue(getHasStateProbProperty(), newHasStateProb);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isProbAssignIn

    public PR_OWLTable getIsProbAssignIn() {
        return (PR_OWLTable) getPropertyValueAs(getIsProbAssignInProperty(), PR_OWLTable.class);
    }


    public RDFProperty getIsProbAssignInProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isProbAssignIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsProbAssignIn() {
        return getPropertyValueCount(getIsProbAssignInProperty()) > 0;
    }


    public void setIsProbAssignIn(PR_OWLTable newIsProbAssignIn) {
        setPropertyValue(getIsProbAssignInProperty(), newIsProbAssignIn);
    }
}
