package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.*;
import es.upm.dit.gsi.ontology.System;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Failure
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultFailure extends AbstractCodeGeneratorIndividual
         implements Failure {

    public DefaultFailure(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultFailure() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#canBeRepairedWith

    public Set getCanBeRepairedWith() {
        return new HashSet(getPropertyValuesAs(getCanBeRepairedWithProperty(), HealingAction.class));
    }


    public RDFProperty getCanBeRepairedWithProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#canBeRepairedWith";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCanBeRepairedWith() {
        return getPropertyValueCount(getCanBeRepairedWithProperty()) > 0;
    }


    public Iterator listCanBeRepairedWith() {
        return listPropertyValuesAs(getCanBeRepairedWithProperty(), HealingAction.class);
    }


    public void addCanBeRepairedWith(HealingAction newCanBeRepairedWith) {
        addPropertyValue(getCanBeRepairedWithProperty(), newCanBeRepairedWith);
    }


    public void removeCanBeRepairedWith(HealingAction oldCanBeRepairedWith) {
        removePropertyValue(getCanBeRepairedWithProperty(), oldCanBeRepairedWith);
    }


    public void setCanBeRepairedWith(Set newCanBeRepairedWith) {
        setPropertyValues(getCanBeRepairedWithProperty(), newCanBeRepairedWith);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    public System getHasLocation() {
        return (System) getPropertyValueAs(getHasLocationProperty(), System.class);
    }


    public RDFProperty getHasLocationProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasLocation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasLocation() {
        return getPropertyValueCount(getHasLocationProperty()) > 0;
    }


    public void setHasLocation(System newHasLocation) {
        setPropertyValue(getHasLocationProperty(), newHasLocation);
    }
}
