package es.upm.dit.gsi.ontology.impl;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.Exemplar;
import es.upm.dit.gsi.ontology.Input;
import es.upm.dit.gsi.ontology.MFrag;
import es.upm.dit.gsi.ontology.MTheory;
import es.upm.dit.gsi.ontology.Node;
import es.upm.dit.gsi.ontology.OVariable;
import es.upm.dit.gsi.ontology.Resident;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#MFrag
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public class DefaultMFrag extends AbstractCodeGeneratorIndividual
         implements MFrag {

    public DefaultMFrag(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultMFrag() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasExemplar

    public Set getHasExemplar() {
        return new HashSet(getPropertyValuesAs(getHasExemplarProperty(), Exemplar.class));
    }


    public RDFProperty getHasExemplarProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasExemplar";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasExemplar() {
        return getPropertyValueCount(getHasExemplarProperty()) > 0;
    }


    public Iterator listHasExemplar() {
        return listPropertyValuesAs(getHasExemplarProperty(), Exemplar.class);
    }


    public void addHasExemplar(Exemplar newHasExemplar) {
        addPropertyValue(getHasExemplarProperty(), newHasExemplar);
    }


    public void removeHasExemplar(Exemplar oldHasExemplar) {
        removePropertyValue(getHasExemplarProperty(), oldHasExemplar);
    }


    public void setHasExemplar(Set newHasExemplar) {
        setPropertyValues(getHasExemplarProperty(), newHasExemplar);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasInputNode

    public Set getHasInputNode() {
        return new HashSet(getPropertyValuesAs(getHasInputNodeProperty(), Input.class));
    }


    public RDFProperty getHasInputNodeProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasInputNode";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasInputNode() {
        return getPropertyValueCount(getHasInputNodeProperty()) > 0;
    }


    public Iterator listHasInputNode() {
        return listPropertyValuesAs(getHasInputNodeProperty(), Input.class);
    }


    public void addHasInputNode(Input newHasInputNode) {
        addPropertyValue(getHasInputNodeProperty(), newHasInputNode);
    }


    public void removeHasInputNode(Input oldHasInputNode) {
        removePropertyValue(getHasInputNodeProperty(), oldHasInputNode);
    }


    public void setHasInputNode(Set newHasInputNode) {
        setPropertyValues(getHasInputNodeProperty(), newHasInputNode);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasNode

    public Set getHasNode() {
        return new HashSet(getPropertyValuesAs(getHasNodeProperty(), Node.class));
    }


    public RDFProperty getHasNodeProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasNode";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasNode() {
        return getPropertyValueCount(getHasNodeProperty()) > 0;
    }


    public Iterator listHasNode() {
        return listPropertyValuesAs(getHasNodeProperty(), Node.class);
    }


    public void addHasNode(Node newHasNode) {
        addPropertyValue(getHasNodeProperty(), newHasNode);
    }


    public void removeHasNode(Node oldHasNode) {
        removePropertyValue(getHasNodeProperty(), oldHasNode);
    }


    public void setHasNode(Set newHasNode) {
        setPropertyValues(getHasNodeProperty(), newHasNode);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasOVariable

    public Set getHasOVariable() {
        return new HashSet(getPropertyValuesAs(getHasOVariableProperty(), OVariable.class));
    }


    public RDFProperty getHasOVariableProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasOVariable";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasOVariable() {
        return getPropertyValueCount(getHasOVariableProperty()) > 0;
    }


    public Iterator listHasOVariable() {
        return listPropertyValuesAs(getHasOVariableProperty(), OVariable.class);
    }


    public void addHasOVariable(OVariable newHasOVariable) {
        addPropertyValue(getHasOVariableProperty(), newHasOVariable);
    }


    public void removeHasOVariable(OVariable oldHasOVariable) {
        removePropertyValue(getHasOVariableProperty(), oldHasOVariable);
    }


    public void setHasOVariable(Set newHasOVariable) {
        setPropertyValues(getHasOVariableProperty(), newHasOVariable);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasResidentNode

    public Set getHasResidentNode() {
        return new HashSet(getPropertyValuesAs(getHasResidentNodeProperty(), Resident.class));
    }


    public RDFProperty getHasResidentNodeProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasResidentNode";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasResidentNode() {
        return getPropertyValueCount(getHasResidentNodeProperty()) > 0;
    }


    public Iterator listHasResidentNode() {
        return listPropertyValuesAs(getHasResidentNodeProperty(), Resident.class);
    }


    public void addHasResidentNode(Resident newHasResidentNode) {
        addPropertyValue(getHasResidentNodeProperty(), newHasResidentNode);
    }


    public void removeHasResidentNode(Resident oldHasResidentNode) {
        removePropertyValue(getHasResidentNodeProperty(), oldHasResidentNode);
    }


    public void setHasResidentNode(Set newHasResidentNode) {
        setPropertyValues(getHasResidentNodeProperty(), newHasResidentNode);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isMFragOf

    public Set getIsMFragOf() {
        return new HashSet(getPropertyValuesAs(getIsMFragOfProperty(), MTheory.class));
    }


    public RDFProperty getIsMFragOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isMFragOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsMFragOf() {
        return getPropertyValueCount(getIsMFragOfProperty()) > 0;
    }


    public Iterator listIsMFragOf() {
        return listPropertyValuesAs(getIsMFragOfProperty(), MTheory.class);
    }


    public void addIsMFragOf(MTheory newIsMFragOf) {
        addPropertyValue(getIsMFragOfProperty(), newIsMFragOf);
    }


    public void removeIsMFragOf(MTheory oldIsMFragOf) {
        removePropertyValue(getIsMFragOfProperty(), oldIsMFragOf);
    }


    public void setIsMFragOf(Set newIsMFragOf) {
        setPropertyValues(getIsMFragOfProperty(), newIsMFragOf);
    }
}
