package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.AvailableAction;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#AvailableAction
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultAvailableAction extends DefaultAction
         implements AvailableAction {

    public DefaultAvailableAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultAvailableAction() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#available

    public boolean getAvailable() {
        return getPropertyValueLiteral(getAvailableProperty()).getBoolean();
    }


    public RDFProperty getAvailableProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#available";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAvailable() {
        return getPropertyValueCount(getAvailableProperty()) > 0;
    }


    public void setAvailable(boolean newAvailable) {
        setPropertyValue(getAvailableProperty(), new java.lang.Boolean(newAvailable));
    }
}
