package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.commune.ontology.HealingAction;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#HealingAction
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultHealingAction extends DefaultEnvironmentAction
         implements HealingAction {

    public DefaultHealingAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultHealingAction() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#repairsFailure

    public Collection getRepairsFailure() {
        return getPropertyValuesAs(getRepairsFailureProperty(), Failure.class);
    }


    public RDFProperty getRepairsFailureProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#repairsFailure";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRepairsFailure() {
        return getPropertyValueCount(getRepairsFailureProperty()) > 0;
    }


    public Iterator listRepairsFailure() {
        return listPropertyValuesAs(getRepairsFailureProperty(), Failure.class);
    }


    public void addRepairsFailure(Failure newRepairsFailure) {
        addPropertyValue(getRepairsFailureProperty(), newRepairsFailure);
    }


    public void removeRepairsFailure(Failure oldRepairsFailure) {
        removePropertyValue(getRepairsFailureProperty(), oldRepairsFailure);
    }


    public void setRepairsFailure(Collection newRepairsFailure) {
        setPropertyValues(getRepairsFailureProperty(), newRepairsFailure);
    }
}
