package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.Entity;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#Entity
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultEntity extends AbstractCodeGeneratorIndividual
         implements Entity {

    public DefaultEntity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultEntity() {
    }
}
