package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.Hypothesis;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Hypothesis
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultHypothesis extends AbstractCodeGeneratorIndividual
         implements Hypothesis {

    public DefaultHypothesis(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultHypothesis() {
    }



    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis

    public HypothesisNode getHasBayesianHypothesis() {
        return (HypothesisNode) getPropertyValueAs(getHasBayesianHypothesisProperty(), HypothesisNode.class);
    }


    public RDFProperty getHasBayesianHypothesisProperty() {
        final String uri = "http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasBayesianHypothesis() {
        return getPropertyValueCount(getHasBayesianHypothesisProperty()) > 0;
    }


    public void setHasBayesianHypothesis(HypothesisNode newHasBayesianHypothesis) {
        setPropertyValue(getHasBayesianHypothesisProperty(), newHasBayesianHypothesis);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence

    public float getHypothesisConfidence() {
        return getPropertyValueLiteral(getHypothesisConfidenceProperty()).getFloat();
    }


    public RDFProperty getHypothesisConfidenceProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHypothesisConfidence() {
        return getPropertyValueCount(getHypothesisConfidenceProperty()) > 0;
    }


    public void setHypothesisConfidence(float newHypothesisConfidence) {
        setPropertyValue(getHypothesisConfidenceProperty(), new java.lang.Float(newHypothesisConfidence));
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure

    public Failure getRepresentsPossibleFailure() {
        return (Failure) getPropertyValueAs(getRepresentsPossibleFailureProperty(), Failure.class);
    }


    public RDFProperty getRepresentsPossibleFailureProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRepresentsPossibleFailure() {
        return getPropertyValueCount(getRepresentsPossibleFailureProperty()) > 0;
    }


    public void setRepresentsPossibleFailure(Failure newRepresentsPossibleFailure) {
        setPropertyValue(getRepresentsPossibleFailureProperty(), newRepresentsPossibleFailure);
    }
}
