package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Hypothesis
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Hypothesis extends OWLIndividual {

    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis

    HypothesisNode getHasBayesianHypothesis();

    RDFProperty getHasBayesianHypothesisProperty();

    boolean hasHasBayesianHypothesis();

    void setHasBayesianHypothesis(HypothesisNode newHasBayesianHypothesis);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence

    float getHypothesisConfidence();

    RDFProperty getHypothesisConfidenceProperty();

    boolean hasHypothesisConfidence();

    void setHypothesisConfidence(float newHypothesisConfidence);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure

    Failure getRepresentsPossibleFailure();

    RDFProperty getRepresentsPossibleFailureProperty();

    boolean hasRepresentsPossibleFailure();

    void setRepresentsPossibleFailure(Failure newRepresentsPossibleFailure);
}
