package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#KillProcess
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface KillProcess extends HealingAction {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasPrecondition

    Collection getHasPrecondition();

    RDFProperty getHasPreconditionProperty();

    boolean hasHasPrecondition();

    Iterator listHasPrecondition();

    void addHasPrecondition(Object newHasPrecondition);

    void removeHasPrecondition(Object oldHasPrecondition);

    void setHasPrecondition(Collection newHasPrecondition);
}
