package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#MonitoringAction
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface MonitoringAction extends EnvironmentAction {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#resultSymptom

    Collection getResultSymptom();

    RDFProperty getResultSymptomProperty();

    boolean hasResultSymptom();

    Iterator listResultSymptom();

    void addResultSymptom(Symptom newResultSymptom);

    void removeResultSymptom(Symptom oldResultSymptom);

    void setResultSymptom(Collection newResultSymptom);
}
