package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Node
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Node extends OWLIndividual {
}
