package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Observation
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Observation extends OWLIndividual {

    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation

    ObservationNode getHasBayesianObservation();

    RDFProperty getHasBayesianObservationProperty();

    boolean hasHasBayesianObservation();

    void setHasBayesianObservation(ObservationNode newHasBayesianObservation);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#observationType

    String getObservationType();

    RDFProperty getObservationTypeProperty();

    boolean hasObservationType();

    void setObservationType(String newObservationType);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#observationValue

    String getObservationValue();

    RDFProperty getObservationValueProperty();

    boolean hasObservationValue();

    void setObservationValue(String newObservationValue);
}
