package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#RequiredStreamingSessionCondition
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface RequiredStreamingSessionCondition extends Condition {
}
