package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#System
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface System extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasAgentResiding

    Collection getHasAgentResiding();

    RDFProperty getHasAgentResidingProperty();

    boolean hasHasAgentResiding();

    Iterator listHasAgentResiding();

    void addHasAgentResiding(Agent newHasAgentResiding);

    void removeHasAgentResiding(Agent oldHasAgentResiding);

    void setHasAgentResiding(Collection newHasAgentResiding);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasData

    Collection getHasData();

    RDFProperty getHasDataProperty();

    boolean hasHasData();

    Iterator listHasData();

    void addHasData(Variable newHasData);

    void removeHasData(Variable oldHasData);

    void setHasData(Collection newHasData);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasFailure

    Collection getHasFailure();

    RDFProperty getHasFailureProperty();

    boolean hasHasFailure();

    Iterator listHasFailure();

    void addHasFailure(Failure newHasFailure);

    void removeHasFailure(Failure oldHasFailure);

    void setHasFailure(Collection newHasFailure);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#isComposedBy

    Collection getIsComposedBy();

    RDFProperty getIsComposedByProperty();

    boolean hasIsComposedBy();

    Iterator listIsComposedBy();

    void addIsComposedBy(Subsystem newIsComposedBy);

    void removeIsComposedBy(Subsystem oldIsComposedBy);

    void setIsComposedBy(Collection newIsComposedBy);
}
