package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.commune.ontology.Actor;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Actor
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultActor extends AbstractCodeGeneratorIndividual
         implements Actor {

    public DefaultActor(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultActor() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#canPerform

    public Collection getCanPerform() {
        return getPropertyValuesAs(getCanPerformProperty(), Action.class);
    }


    public RDFProperty getCanPerformProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#canPerform";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCanPerform() {
        return getPropertyValueCount(getCanPerformProperty()) > 0;
    }


    public Iterator listCanPerform() {
        return listPropertyValuesAs(getCanPerformProperty(), Action.class);
    }


    public void addCanPerform(Action newCanPerform) {
        addPropertyValue(getCanPerformProperty(), newCanPerform);
    }


    public void removeCanPerform(Action oldCanPerform) {
        removePropertyValue(getCanPerformProperty(), oldCanPerform);
    }


    public void setCanPerform(Collection newCanPerform) {
        setPropertyValues(getCanPerformProperty(), newCanPerform);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasPerformed

    public Collection getHasPerformed() {
        return getPropertyValuesAs(getHasPerformedProperty(), PerformedAction.class);
    }


    public RDFProperty getHasPerformedProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasPerformed";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasPerformed() {
        return getPropertyValueCount(getHasPerformedProperty()) > 0;
    }


    public Iterator listHasPerformed() {
        return listPropertyValuesAs(getHasPerformedProperty(), PerformedAction.class);
    }


    public void addHasPerformed(PerformedAction newHasPerformed) {
        addPropertyValue(getHasPerformedProperty(), newHasPerformed);
    }


    public void removeHasPerformed(PerformedAction oldHasPerformed) {
        removePropertyValue(getHasPerformedProperty(), oldHasPerformed);
    }


    public void setHasPerformed(Collection newHasPerformed) {
        setPropertyValues(getHasPerformedProperty(), newHasPerformed);
    }
}
