package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.commune.ontology.Diagnosis;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Diagnosis
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultDiagnosis extends AbstractCodeGeneratorIndividual
         implements Diagnosis {

    public DefaultDiagnosis(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultDiagnosis() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasHypothesis

    public Collection getHasHypothesis() {
        return getPropertyValuesAs(getHasHypothesisProperty(), Hypothesis.class);
    }


    public RDFProperty getHasHypothesisProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasHypothesis";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasHypothesis() {
        return getPropertyValueCount(getHasHypothesisProperty()) > 0;
    }


    public Iterator listHasHypothesis() {
        return listPropertyValuesAs(getHasHypothesisProperty(), Hypothesis.class);
    }


    public void addHasHypothesis(Hypothesis newHasHypothesis) {
        addPropertyValue(getHasHypothesisProperty(), newHasHypothesis);
    }


    public void removeHasHypothesis(Hypothesis oldHasHypothesis) {
        removePropertyValue(getHasHypothesisProperty(), oldHasHypothesis);
    }


    public void setHasHypothesis(Collection newHasHypothesis) {
        setPropertyValues(getHasHypothesisProperty(), newHasHypothesis);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedAction

    public Collection getPerformedAction() {
        return getPropertyValuesAs(getPerformedActionProperty(), PerformedAction.class);
    }


    public RDFProperty getPerformedActionProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#performedAction";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformedAction() {
        return getPropertyValueCount(getPerformedActionProperty()) > 0;
    }


    public Iterator listPerformedAction() {
        return listPropertyValuesAs(getPerformedActionProperty(), PerformedAction.class);
    }


    public void addPerformedAction(PerformedAction newPerformedAction) {
        addPropertyValue(getPerformedActionProperty(), newPerformedAction);
    }


    public void removePerformedAction(PerformedAction oldPerformedAction) {
        removePropertyValue(getPerformedActionProperty(), oldPerformedAction);
    }


    public void setPerformedAction(Collection newPerformedAction) {
        setPropertyValues(getPerformedActionProperty(), newPerformedAction);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedHealingAction

    public Collection getPerformedHealingAction() {
        return getPropertyValues(getPerformedHealingActionProperty());
    }


    public RDFProperty getPerformedHealingActionProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#performedHealingAction";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformedHealingAction() {
        return getPropertyValueCount(getPerformedHealingActionProperty()) > 0;
    }


    public Iterator listPerformedHealingAction() {
        return listPropertyValues(getPerformedHealingActionProperty());
    }


    public void addPerformedHealingAction(Object newPerformedHealingAction) {
        addPropertyValue(getPerformedHealingActionProperty(), newPerformedHealingAction);
    }


    public void removePerformedHealingAction(Object oldPerformedHealingAction) {
        removePropertyValue(getPerformedHealingActionProperty(), oldPerformedHealingAction);
    }


    public void setPerformedHealingAction(Collection newPerformedHealingAction) {
        setPropertyValues(getPerformedHealingActionProperty(), newPerformedHealingAction);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedMonitoringAction

    public Collection getPerformedMonitoringAction() {
        return getPropertyValues(getPerformedMonitoringActionProperty());
    }


    public RDFProperty getPerformedMonitoringActionProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#performedMonitoringAction";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformedMonitoringAction() {
        return getPropertyValueCount(getPerformedMonitoringActionProperty()) > 0;
    }


    public Iterator listPerformedMonitoringAction() {
        return listPropertyValues(getPerformedMonitoringActionProperty());
    }


    public void addPerformedMonitoringAction(Object newPerformedMonitoringAction) {
        addPropertyValue(getPerformedMonitoringActionProperty(), newPerformedMonitoringAction);
    }


    public void removePerformedMonitoringAction(Object oldPerformedMonitoringAction) {
        removePropertyValue(getPerformedMonitoringActionProperty(), oldPerformedMonitoringAction);
    }


    public void setPerformedMonitoringAction(Collection newPerformedMonitoringAction) {
        setPropertyValues(getPerformedMonitoringActionProperty(), newPerformedMonitoringAction);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedTestAction

    public Collection getPerformedTestAction() {
        return getPropertyValues(getPerformedTestActionProperty());
    }


    public RDFProperty getPerformedTestActionProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#performedTestAction";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformedTestAction() {
        return getPropertyValueCount(getPerformedTestActionProperty()) > 0;
    }


    public Iterator listPerformedTestAction() {
        return listPropertyValues(getPerformedTestActionProperty());
    }


    public void addPerformedTestAction(Object newPerformedTestAction) {
        addPropertyValue(getPerformedTestActionProperty(), newPerformedTestAction);
    }


    public void removePerformedTestAction(Object oldPerformedTestAction) {
        removePropertyValue(getPerformedTestActionProperty(), oldPerformedTestAction);
    }


    public void setPerformedTestAction(Collection newPerformedTestAction) {
        setPropertyValues(getPerformedTestActionProperty(), newPerformedTestAction);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#startedBySymptom

    public Collection getStartedBySymptom() {
        return getPropertyValuesAs(getStartedBySymptomProperty(), Symptom.class);
    }


    public RDFProperty getStartedBySymptomProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#startedBySymptom";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasStartedBySymptom() {
        return getPropertyValueCount(getStartedBySymptomProperty()) > 0;
    }


    public Iterator listStartedBySymptom() {
        return listPropertyValuesAs(getStartedBySymptomProperty(), Symptom.class);
    }


    public void addStartedBySymptom(Symptom newStartedBySymptom) {
        addPropertyValue(getStartedBySymptomProperty(), newStartedBySymptom);
    }


    public void removeStartedBySymptom(Symptom oldStartedBySymptom) {
        removePropertyValue(getStartedBySymptomProperty(), oldStartedBySymptom);
    }


    public void setStartedBySymptom(Collection newStartedBySymptom) {
        setPropertyValues(getStartedBySymptomProperty(), newStartedBySymptom);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#status

    public String getStatus() {
        return (String) getPropertyValue(getStatusProperty());
    }


    public RDFProperty getStatusProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#status";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasStatus() {
        return getPropertyValueCount(getStatusProperty()) > 0;
    }


    public void setStatus(String newStatus) {
        setPropertyValue(getStatusProperty(), newStatus);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#whenHasFinished

    public RDFSLiteral getWhenHasFinished() {
        return (RDFSLiteral) getPropertyValue(getWhenHasFinishedProperty());
    }


    public RDFProperty getWhenHasFinishedProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#whenHasFinished";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasWhenHasFinished() {
        return getPropertyValueCount(getWhenHasFinishedProperty()) > 0;
    }


    public void setWhenHasFinished(RDFSLiteral newWhenHasFinished) {
        setPropertyValue(getWhenHasFinishedProperty(), newWhenHasFinished);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#whenHasStarted

    public RDFSLiteral getWhenHasStarted() {
        return (RDFSLiteral) getPropertyValue(getWhenHasStartedProperty());
    }


    public RDFProperty getWhenHasStartedProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#whenHasStarted";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasWhenHasStarted() {
        return getPropertyValueCount(getWhenHasStartedProperty()) > 0;
    }


    public void setWhenHasStarted(RDFSLiteral newWhenHasStarted) {
        setPropertyValue(getWhenHasStartedProperty(), newWhenHasStarted);
    }
}
