package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.commune.ontology.DetectedJitter;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#DetectedJitter
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultDetectedJitter extends DefaultSymptom
         implements DetectedJitter {

    public DefaultDetectedJitter(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultDetectedJitter() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#possibleResults

    public Collection getPossibleResults() {
        return getPropertyValues(getPossibleResultsProperty());
    }


    public RDFProperty getPossibleResultsProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#possibleResults";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPossibleResults() {
        return getPropertyValueCount(getPossibleResultsProperty()) > 0;
    }


    public Iterator listPossibleResults() {
        return listPropertyValues(getPossibleResultsProperty());
    }


    public void addPossibleResults(String newPossibleResults) {
        addPropertyValue(getPossibleResultsProperty(), newPossibleResults);
    }


    public void removePossibleResults(String oldPossibleResults) {
        removePropertyValue(getPossibleResultsProperty(), oldPossibleResults);
    }


    public void setPossibleResults(Collection newPossibleResults) {
        setPropertyValues(getPossibleResultsProperty(), newPossibleResults);
    }
}
