package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.RuleGroup;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://swrl.stanford.edu/ontologies/3.3/swrla.owl#RuleGroup
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultRuleGroup extends DefaultEntity
         implements RuleGroup {

    public DefaultRuleGroup(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultRuleGroup() {
    }



    // Property http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleGroupEnabled

    public boolean getIsRuleGroupEnabled() {
        return getPropertyValueLiteral(getIsRuleGroupEnabledProperty()).getBoolean();
    }


    public RDFProperty getIsRuleGroupEnabledProperty() {
        final String uri = "http://swrl.stanford.edu/ontologies/3.3/swrla.owl#isRuleGroupEnabled";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsRuleGroupEnabled() {
        return getPropertyValueCount(getIsRuleGroupEnabledProperty()) > 0;
    }


    public void setIsRuleGroupEnabled(boolean newIsRuleGroupEnabled) {
        setPropertyValue(getIsRuleGroupEnabledProperty(), new java.lang.Boolean(newIsRuleGroupEnabled));
    }
}
