package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.ConnectionFailure;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#ConnectionFailure
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultConnectionFailure extends DefaultFailure
         implements ConnectionFailure {

    public DefaultConnectionFailure(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultConnectionFailure() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    public Connection getHasLocation() {
        return (Connection) getPropertyValueAs(getHasLocationProperty(), Connection.class);
    }


    public RDFProperty getHasLocationProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasLocation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasLocation() {
        return getPropertyValueCount(getHasLocationProperty()) > 0;
    }


    public void setHasLocation(Connection newHasLocation) {
        setPropertyValue(getHasLocationProperty(), newHasLocation);
    }
}
