package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.PC;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#PC
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultPC extends DefaultDevice
         implements PC {

    public DefaultPC(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultPC() {
    }
}
