package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.ConnectivityTestAction;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/P2PDiagnosis.owl#ConnectivityTestAction
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultConnectivityTestAction extends DefaultTestAction
         implements ConnectivityTestAction {

    public DefaultConnectivityTestAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultConnectivityTestAction() {
    }
}
