package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.SatisfiedCondition;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#SatisfiedCondition
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultSatisfiedCondition extends DefaultCondition
         implements SatisfiedCondition {

    public DefaultSatisfiedCondition(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultSatisfiedCondition() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#satisfied

    public boolean getSatisfied() {
        return getPropertyValueLiteral(getSatisfiedProperty()).getBoolean();
    }


    public RDFProperty getSatisfiedProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#satisfied";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSatisfied() {
        return getPropertyValueCount(getSatisfiedProperty()) > 0;
    }


    public void setSatisfied(boolean newSatisfied) {
        setPropertyValue(getSatisfiedProperty(), new java.lang.Boolean(newSatisfied));
    }
}
