package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.commune.ontology.System;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#System
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultSystem extends AbstractCodeGeneratorIndividual
         implements System {

    public DefaultSystem(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultSystem() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasAgentResiding

    public Collection getHasAgentResiding() {
        return getPropertyValuesAs(getHasAgentResidingProperty(), Agent.class);
    }


    public RDFProperty getHasAgentResidingProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasAgentResiding";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasAgentResiding() {
        return getPropertyValueCount(getHasAgentResidingProperty()) > 0;
    }


    public Iterator listHasAgentResiding() {
        return listPropertyValuesAs(getHasAgentResidingProperty(), Agent.class);
    }


    public void addHasAgentResiding(Agent newHasAgentResiding) {
        addPropertyValue(getHasAgentResidingProperty(), newHasAgentResiding);
    }


    public void removeHasAgentResiding(Agent oldHasAgentResiding) {
        removePropertyValue(getHasAgentResidingProperty(), oldHasAgentResiding);
    }


    public void setHasAgentResiding(Collection newHasAgentResiding) {
        setPropertyValues(getHasAgentResidingProperty(), newHasAgentResiding);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasData

    public Collection getHasData() {
        return getPropertyValuesAs(getHasDataProperty(), Variable.class);
    }


    public RDFProperty getHasDataProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasData";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasData() {
        return getPropertyValueCount(getHasDataProperty()) > 0;
    }


    public Iterator listHasData() {
        return listPropertyValuesAs(getHasDataProperty(), Variable.class);
    }


    public void addHasData(Variable newHasData) {
        addPropertyValue(getHasDataProperty(), newHasData);
    }


    public void removeHasData(Variable oldHasData) {
        removePropertyValue(getHasDataProperty(), oldHasData);
    }


    public void setHasData(Collection newHasData) {
        setPropertyValues(getHasDataProperty(), newHasData);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasFailure

    public Collection getHasFailure() {
        return getPropertyValuesAs(getHasFailureProperty(), Failure.class);
    }


    public RDFProperty getHasFailureProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasFailure";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasFailure() {
        return getPropertyValueCount(getHasFailureProperty()) > 0;
    }


    public Iterator listHasFailure() {
        return listPropertyValuesAs(getHasFailureProperty(), Failure.class);
    }


    public void addHasFailure(Failure newHasFailure) {
        addPropertyValue(getHasFailureProperty(), newHasFailure);
    }


    public void removeHasFailure(Failure oldHasFailure) {
        removePropertyValue(getHasFailureProperty(), oldHasFailure);
    }


    public void setHasFailure(Collection newHasFailure) {
        setPropertyValues(getHasFailureProperty(), newHasFailure);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#isComposedBy

    public Collection getIsComposedBy() {
        return getPropertyValuesAs(getIsComposedByProperty(), Subsystem.class);
    }


    public RDFProperty getIsComposedByProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#isComposedBy";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsComposedBy() {
        return getPropertyValueCount(getIsComposedByProperty()) > 0;
    }


    public Iterator listIsComposedBy() {
        return listPropertyValuesAs(getIsComposedByProperty(), Subsystem.class);
    }


    public void addIsComposedBy(Subsystem newIsComposedBy) {
        addPropertyValue(getIsComposedByProperty(), newIsComposedBy);
    }


    public void removeIsComposedBy(Subsystem oldIsComposedBy) {
        removePropertyValue(getIsComposedByProperty(), oldIsComposedBy);
    }


    public void setIsComposedBy(Collection newIsComposedBy) {
        setPropertyValues(getIsComposedByProperty(), newIsComposedBy);
    }
}
