package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.Observation;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Observation
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultObservation extends AbstractCodeGeneratorIndividual
         implements Observation {

    public DefaultObservation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultObservation() {
    }



    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation

    public ObservationNode getHasBayesianObservation() {
        return (ObservationNode) getPropertyValueAs(getHasBayesianObservationProperty(), ObservationNode.class);
    }


    public RDFProperty getHasBayesianObservationProperty() {
        final String uri = "http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasBayesianObservation() {
        return getPropertyValueCount(getHasBayesianObservationProperty()) > 0;
    }


    public void setHasBayesianObservation(ObservationNode newHasBayesianObservation) {
        setPropertyValue(getHasBayesianObservationProperty(), newHasBayesianObservation);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#observationType

    public String getObservationType() {
        return (String) getPropertyValue(getObservationTypeProperty());
    }


    public RDFProperty getObservationTypeProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#observationType";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasObservationType() {
        return getPropertyValueCount(getObservationTypeProperty()) > 0;
    }


    public void setObservationType(String newObservationType) {
        setPropertyValue(getObservationTypeProperty(), newObservationType);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#observationValue

    public String getObservationValue() {
        return (String) getPropertyValue(getObservationValueProperty());
    }


    public RDFProperty getObservationValueProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#observationValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasObservationValue() {
        return getPropertyValueCount(getObservationValueProperty()) > 0;
    }


    public void setObservationValue(String newObservationValue) {
        setPropertyValue(getObservationValueProperty(), newObservationValue);
    }
}
