package es.upm.dit.gsi.commune.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.commune.ontology.System;
import es.upm.dit.gsi.commune.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Variable
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public class DefaultVariable extends AbstractCodeGeneratorIndividual
         implements Variable {

    public DefaultVariable(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultVariable() {
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#residesIn

    public System getResidesIn() {
        return (System) getPropertyValueAs(getResidesInProperty(), System.class);
    }


    public RDFProperty getResidesInProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#residesIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResidesIn() {
        return getPropertyValueCount(getResidesInProperty()) > 0;
    }


    public void setResidesIn(System newResidesIn) {
        setPropertyValue(getResidesInProperty(), newResidesIn);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#variableType

    public String getVariableType() {
        return (String) getPropertyValue(getVariableTypeProperty());
    }


    public RDFProperty getVariableTypeProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#variableType";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasVariableType() {
        return getPropertyValueCount(getVariableTypeProperty()) > 0;
    }


    public void setVariableType(String newVariableType) {
        setPropertyValue(getVariableTypeProperty(), newVariableType);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#variableValue

    public Object getVariableValue() {
        return (Object) getPropertyValue(getVariableValueProperty());
    }


    public RDFProperty getVariableValueProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#variableValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasVariableValue() {
        return getPropertyValueCount(getVariableValueProperty()) > 0;
    }


    public void setVariableValue(Object newVariableValue) {
        setPropertyValue(getVariableValueProperty(), newVariableValue);
    }
}
