package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Device
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Device extends System, HardwareSystem {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#belongsToNetwork

    Collection getBelongsToNetwork();

    RDFProperty getBelongsToNetworkProperty();

    boolean hasBelongsToNetwork();

    Iterator listBelongsToNetwork();

    void addBelongsToNetwork(Network newBelongsToNetwork);

    void removeBelongsToNetwork(Network oldBelongsToNetwork);

    void setBelongsToNetwork(Collection newBelongsToNetwork);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#isConnectedBy

    Collection getIsConnectedBy();

    RDFProperty getIsConnectedByProperty();

    boolean hasIsConnectedBy();

    Iterator listIsConnectedBy();

    void addIsConnectedBy(Connection newIsConnectedBy);

    void removeIsConnectedBy(Connection oldIsConnectedBy);

    void setIsConnectedBy(Collection newIsConnectedBy);
}
