package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Failure
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Failure extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#canBeRepairedWith

    Collection getCanBeRepairedWith();

    RDFProperty getCanBeRepairedWithProperty();

    boolean hasCanBeRepairedWith();

    Iterator listCanBeRepairedWith();

    void addCanBeRepairedWith(HealingAction newCanBeRepairedWith);

    void removeCanBeRepairedWith(HealingAction oldCanBeRepairedWith);

    void setCanBeRepairedWith(Collection newCanBeRepairedWith);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    Object getHasLocation();

    RDFProperty getHasLocationProperty();

    boolean hasHasLocation();

    void setHasLocation(Object newHasLocation);
}
