package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Network
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Network extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasConnection

    Collection getHasConnection();

    RDFProperty getHasConnectionProperty();

    boolean hasHasConnection();

    Iterator listHasConnection();

    void addHasConnection(Connection newHasConnection);

    void removeHasConnection(Connection oldHasConnection);

    void setHasConnection(Collection newHasConnection);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasDevice

    Collection getHasDevice();

    RDFProperty getHasDeviceProperty();

    boolean hasHasDevice();

    Iterator listHasDevice();

    void addHasDevice(Device newHasDevice);

    void removeHasDevice(Device oldHasDevice);

    void setHasDevice(Collection newHasDevice);
}
