package es.upm.dit.gsi.commune.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Symptom
 *
 * @version generated on Tue Apr 05 14:50:26 CEST 2011
 */
public interface Symptom extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    Object getHasLocation();

    RDFProperty getHasLocationProperty();

    boolean hasHasLocation();

    void setHasLocation(Object newHasLocation);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#observationResult

    Observation getObservationResult();

    RDFProperty getObservationResultProperty();

    boolean hasObservationResult();

    void setObservationResult(Observation newObservationResult);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#startsDiagnosis

    Collection getStartsDiagnosis();

    RDFProperty getStartsDiagnosisProperty();

    boolean hasStartsDiagnosis();

    Iterator listStartsDiagnosis();

    void addStartsDiagnosis(Diagnosis newStartsDiagnosis);

    void removeStartsDiagnosis(Diagnosis oldStartsDiagnosis);

    void setStartsDiagnosis(Collection newStartsDiagnosis);
}
