package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#BooleanRVStates
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface BooleanRVStates extends Entity {

    // Property http://www.pr-owl.org/pr-owl.owl#hasType

    MetaEntity getHasType();

    RDFProperty getHasTypeProperty();

    boolean hasHasType();

    void setHasType(MetaEntity newHasType);


    // Property http://www.pr-owl.org/pr-owl.owl#isGloballyExclusive

    boolean getIsGloballyExclusive();

    RDFProperty getIsGloballyExclusiveProperty();

    boolean hasIsGloballyExclusive();

    void setIsGloballyExclusive(boolean newIsGloballyExclusive);
}
