package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#BuiltInRV
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface BuiltInRV extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#hasContextInstance

    Set getHasContextInstance();

    RDFProperty getHasContextInstanceProperty();

    boolean hasHasContextInstance();

    Iterator listHasContextInstance();

    void addHasContextInstance(Context newHasContextInstance);

    void removeHasContextInstance(Context oldHasContextInstance);

    void setHasContextInstance(Set newHasContextInstance);


    // Property http://www.pr-owl.org/pr-owl.owl#hasInputInstance

    Set getHasInputInstance();

    RDFProperty getHasInputInstanceProperty();

    boolean hasHasInputInstance();

    Iterator listHasInputInstance();

    void addHasInputInstance(Input newHasInputInstance);

    void removeHasInputInstance(Input oldHasInputInstance);

    void setHasInputInstance(Set newHasInputInstance);


    // Property http://www.pr-owl.org/pr-owl.owl#hasPossibleValues

    Set getHasPossibleValues();

    RDFProperty getHasPossibleValuesProperty();

    boolean hasHasPossibleValues();

    Iterator listHasPossibleValues();

    void addHasPossibleValues(BooleanRVStates newHasPossibleValues);

    void removeHasPossibleValues(BooleanRVStates oldHasPossibleValues);

    void setHasPossibleValues(Set newHasPossibleValues);
}
