package es.upm.dit.gsi.ontology;
import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#CondRelationship
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface CondRelationship extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#hasParentName

    Node getHasParentName();

    RDFProperty getHasParentNameProperty();

    boolean hasHasParentName();

    void setHasParentName(Node newHasParentName);


    // Property http://www.pr-owl.org/pr-owl.owl#hasParentState

    Entity getHasParentState();

    RDFProperty getHasParentStateProperty();

    boolean hasHasParentState();

    void setHasParentState(Entity newHasParentState);


    // Property http://www.pr-owl.org/pr-owl.owl#isConditionantOf

    Set getIsConditionantOf();

    RDFProperty getIsConditionantOfProperty();

    boolean hasIsConditionantOf();

    Iterator listIsConditionantOf();

    void addIsConditionantOf(ProbAssign newIsConditionantOf);

    void removeIsConditionantOf(ProbAssign oldIsConditionantOf);

    void setIsConditionantOf(Set newIsConditionantOf);
}
