package es.upm.dit.gsi.ontology;
import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#DeclarativeDist
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface DeclarativeDist extends ProbDist {

    // Property http://www.pr-owl.org/pr-owl.owl#hasDeclaration

    String getHasDeclaration();

    RDFProperty getHasDeclarationProperty();

    boolean hasHasDeclaration();

    void setHasDeclaration(String newHasDeclaration);
}
