package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Diagnosis
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Diagnosis extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasHypothesis

    Set getHasHypothesis();

    RDFProperty getHasHypothesisProperty();

    boolean hasHasHypothesis();

    Iterator listHasHypothesis();

    void addHasHypothesis(Hypothesis newHasHypothesis);

    void removeHasHypothesis(Hypothesis oldHasHypothesis);

    void setHasHypothesis(Set newHasHypothesis);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#id

    String getId();

    RDFProperty getIdProperty();

    boolean hasId();

    void setId(String newId);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedAction

    Set getPerformedAction();

    RDFProperty getPerformedActionProperty();

    boolean hasPerformedAction();

    Iterator listPerformedAction();

    void addPerformedAction(PerformedAction newPerformedAction);

    void removePerformedAction(PerformedAction oldPerformedAction);

    void setPerformedAction(Set newPerformedAction);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedHealingAction

    Set getPerformedHealingAction();

    RDFProperty getPerformedHealingActionProperty();

    boolean hasPerformedHealingAction();

    Iterator listPerformedHealingAction();

    void addPerformedHealingAction(Object newPerformedHealingAction);

    void removePerformedHealingAction(Object oldPerformedHealingAction);

    void setPerformedHealingAction(Set newPerformedHealingAction);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#performedTestAction

    Set getPerformedTestAction();

    RDFProperty getPerformedTestActionProperty();

    boolean hasPerformedTestAction();

    Iterator listPerformedTestAction();

    void addPerformedTestAction(Object newPerformedTestAction);

    void removePerformedTestAction(Object oldPerformedTestAction);

    void setPerformedTestAction(Set newPerformedTestAction);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#startedBySymptom

    Set getStartedBySymptom();

    RDFProperty getStartedBySymptomProperty();

    boolean hasStartedBySymptom();

    Iterator listStartedBySymptom();

    void addStartedBySymptom(Symptom newStartedBySymptom);

    void removeStartedBySymptom(Symptom oldStartedBySymptom);

    void setStartedBySymptom(Set newStartedBySymptom);
}
