package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Finding_input
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface Finding_input extends Input {

    // Property http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf

    Finding_res getIsInputInstanceOf();

    RDFProperty getIsInputInstanceOfProperty();

    boolean hasIsInputInstanceOf();

    void setIsInputInstanceOf(Finding_res newIsInputInstanceOf);


    // Property http://www.pr-owl.org/pr-owl.owl#isInputNodeIn

    Set getIsInputNodeIn();

    RDFProperty getIsInputNodeInProperty();

    boolean hasIsInputNodeIn();

    Iterator listIsInputNodeIn();

    void addIsInputNodeIn(Finding_MFrag newIsInputNodeIn);

    void removeIsInputNodeIn(Finding_MFrag oldIsInputNodeIn);

    void setIsInputNodeIn(Set newIsInputNodeIn);


    // Property http://www.pr-owl.org/pr-owl.owl#isParentOf

    Set<Finding_res> getIsParentOf();

    RDFProperty getIsParentOfProperty();

    boolean hasIsParentOf();

    void setIsParentOf(Finding_res newIsParentOf);
}
