package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Hypothesis
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Hypothesis extends OWLIndividual {

    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianHypothesis

    Set getHasBayesianHypothesis();

    RDFProperty getHasBayesianHypothesisProperty();

    boolean hasHasBayesianHypothesis();

    Iterator listHasBayesianHypothesis();

    void addHasBayesianHypothesis(HypothesisNode newHasBayesianHypothesis);

    void removeHasBayesianHypothesis(HypothesisNode oldHasBayesianHypothesis);

    void setHasBayesianHypothesis(Set newHasBayesianHypothesis);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hypothesisConfidence

    float getHypothesisConfidence();

    RDFProperty getHypothesisConfidenceProperty();

    boolean hasHypothesisConfidence();

    void setHypothesisConfidence(float newHypothesisConfidence);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#representsPossibleFailure

    Failure getRepresentsPossibleFailure();

    RDFProperty getRepresentsPossibleFailureProperty();

    boolean hasRepresentsPossibleFailure();

    void setRepresentsPossibleFailure(Failure newRepresentsPossibleFailure);
}
