package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#PerformedAction
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface PerformedAction extends Action {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasBeenPerformedBy

    Set getHasBeenPerformedBy();

    RDFProperty getHasBeenPerformedByProperty();

    boolean hasHasBeenPerformedBy();

    Iterator listHasBeenPerformedBy();

    void addHasBeenPerformedBy(Actor newHasBeenPerformedBy);

    void removeHasBeenPerformedBy(Actor oldHasBeenPerformedBy);

    void setHasBeenPerformedBy(Set newHasBeenPerformedBy);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#performed

    boolean getPerformed();

    RDFProperty getPerformedProperty();

    boolean hasPerformed();

    void setPerformed(boolean newPerformed);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#successfullyPerformed

    boolean getSuccessfullyPerformed();

    RDFProperty getSuccessfullyPerformedProperty();

    boolean hasSuccessfullyPerformed();

    void setSuccessfullyPerformed(boolean newSuccessfullyPerformed);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#whenHasBeenPerformed

    RDFSLiteral getWhenHasBeenPerformed();

    RDFProperty getWhenHasBeenPerformedProperty();

    boolean hasWhenHasBeenPerformed();

    void setWhenHasBeenPerformed(RDFSLiteral newWhenHasBeenPerformed);
}
