package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Subsystem
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Subsystem extends System {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#isPartOf

    Set getIsPartOf();

    RDFProperty getIsPartOfProperty();

    boolean hasIsPartOf();

    Iterator listIsPartOf();

    void addIsPartOf(System newIsPartOf);

    void removeIsPartOf(System oldIsPartOf);

    void setIsPartOf(Set newIsPartOf);
}
