package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Symptom
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Symptom extends OWLIndividual {

    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation

    Set getHasBayesianObservation();

    RDFProperty getHasBayesianObservationProperty();

    boolean hasHasBayesianObservation();

    Iterator listHasBayesianObservation();

    void addHasBayesianObservation(ObservationNode newHasBayesianObservation);

    void removeHasBayesianObservation(ObservationNode oldHasBayesianObservation);

    void setHasBayesianObservation(Set newHasBayesianObservation);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    System getHasLocation();

    RDFProperty getHasLocationProperty();

    boolean hasHasLocation();

    void setHasLocation(System newHasLocation);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#startsDiagnosis

    Set getStartsDiagnosis();

    RDFProperty getStartsDiagnosisProperty();

    boolean hasStartsDiagnosis();

    Iterator listStartsDiagnosis();

    void addStartsDiagnosis(Diagnosis newStartsDiagnosis);

    void removeStartsDiagnosis(Diagnosis oldStartsDiagnosis);

    void setStartsDiagnosis(Set newStartsDiagnosis);
}
