package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Variable
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Variable extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#residesIn

    System getResidesIn();

    RDFProperty getResidesInProperty();

    boolean hasResidesIn();

    void setResidesIn(System newResidesIn);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#variableType

    String getVariableType();

    RDFProperty getVariableTypeProperty();

    boolean hasVariableType();

    void setVariableType(String newVariableType);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#variableValue

    Object getVariableValue();

    RDFProperty getVariableValueProperty();

    boolean hasVariableValue();

    void setVariableValue(Object newVariableValue);
}
