package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ArgRelationship
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface ArgRelationship extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#hasArgNumber

    RDFSLiteral getHasArgNumber();

    RDFProperty getHasArgNumberProperty();

    boolean hasHasArgNumber();

    void setHasArgNumber(RDFSLiteral newHasArgNumber);


    // Property http://www.pr-owl.org/pr-owl.owl#hasArgTerm

    Object getHasArgTerm();

    RDFProperty getHasArgTermProperty();

    boolean hasHasArgTerm();

    void setHasArgTerm(Object newHasArgTerm);


    // Property http://www.pr-owl.org/pr-owl.owl#isArgumentOf

    Node getIsArgumentOf();

    RDFProperty getIsArgumentOfProperty();

    boolean hasIsArgumentOf();

    void setIsArgumentOf(Node newIsArgumentOf);
}
