package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#AvailableAction
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface AvailableAction extends Action {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#available

    boolean getAvailable();

    RDFProperty getAvailableProperty();

    boolean hasAvailable();

    void setAvailable(boolean newAvailable);
}
