package es.upm.dit.gsi.ontology;
import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#CategoricalRVState
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface CategoricalRVState extends Entity {

    // Property http://www.pr-owl.org/pr-owl.owl#hasType

    MetaEntity getHasType();

    RDFProperty getHasTypeProperty();

    boolean hasHasType();

    void setHasType(MetaEntity newHasType);


    // Property http://www.pr-owl.org/pr-owl.owl#isGloballyExclusive

    Set getIsGloballyExclusive();

    RDFProperty getIsGloballyExclusiveProperty();

    boolean hasIsGloballyExclusive();

    Iterator listIsGloballyExclusive();

    void addIsGloballyExclusive(Resident newIsGloballyExclusive);

    void removeIsGloballyExclusive(Resident oldIsGloballyExclusive);

    void setIsGloballyExclusive(Set newIsGloballyExclusive);
}
