package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Connection
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Connection extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#connectsSystem

    Set getConnectsSystem();

    RDFProperty getConnectsSystemProperty();

    boolean hasConnectsSystem();

    Iterator listConnectsSystem();

    void addConnectsSystem(Device newConnectsSystem);

    void removeConnectsSystem(Device oldConnectsSystem);

    void setConnectsSystem(Set newConnectsSystem);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#id

    String getId();

    RDFProperty getIdProperty();

    boolean hasId();

    void setId(String newId);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#isPartOfNetwork

    Set getIsPartOfNetwork();

    RDFProperty getIsPartOfNetworkProperty();

    boolean hasIsPartOfNetwork();

    Iterator listIsPartOfNetwork();

    void addIsPartOfNetwork(Network newIsPartOfNetwork);

    void removeIsPartOfNetwork(Network oldIsPartOfNetwork);

    void setIsPartOfNetwork(Set newIsPartOfNetwork);
}
