package es.upm.dit.gsi.ontology;

import java.util.Set;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#DeclarativeDist
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface DeclarativeDist extends ProbDist {

    // Property http://www.pr-owl.org/pr-owl.owl#hasDeclaration

    String getHasDeclaration();

    RDFProperty getHasDeclarationProperty();

    boolean hasHasDeclaration();

    void setHasDeclaration(String newHasDeclaration);


    // Property http://www.pr-owl.org/pr-owl.owl#isProbDistOf

    Resident getIsProbDistOf();

    RDFProperty getIsProbDistOfProperty();

    boolean hasIsProbDistOf();

    void setIsProbDistOf(Resident newIsProbDistOf);


    // Property http://www.pr-owl.org/pr-owl.owl#isRepresentedAs

    Object getIsRepresentedAs();

    RDFProperty getIsRepresentedAsProperty();

    boolean hasIsRepresentedAs();

    void setIsRepresentedAs(Object newIsRepresentedAs);
}
