package es.upm.dit.gsi.ontology;
import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Exemplar
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface Exemplar extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#isArgTermIn

    Set getIsArgTermIn();

    RDFProperty getIsArgTermInProperty();

    boolean hasIsArgTermIn();

    Iterator listIsArgTermIn();

    void addIsArgTermIn(ArgRelationship newIsArgTermIn);

    void removeIsArgTermIn(ArgRelationship oldIsArgTermIn);

    void setIsArgTermIn(Set newIsArgTermIn);


    // Property http://www.pr-owl.org/pr-owl.owl#isExemplarIn

    Set getIsExemplarIn();

    RDFProperty getIsExemplarInProperty();

    boolean hasIsExemplarIn();

    Iterator listIsExemplarIn();

    void addIsExemplarIn(MFrag newIsExemplarIn);

    void removeIsExemplarIn(MFrag oldIsExemplarIn);

    void setIsExemplarIn(Set newIsExemplarIn);


    // Property http://www.pr-owl.org/pr-owl.owl#representsOVar

    OVariable getRepresentsOVar();

    RDFProperty getRepresentsOVarProperty();

    boolean hasRepresentsOVar();

    void setRepresentsOVar(OVariable newRepresentsOVar);
}
