package es.upm.dit.gsi.ontology;
import java.util.Set;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Finding_MFrag
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface Finding_MFrag extends MFrag {

    // Property http://www.pr-owl.org/pr-owl.owl#hasInputNode

    Set<Finding_input> getHasInputNode();

    RDFProperty getHasInputNodeProperty();

    boolean hasHasInputNode();

    void setHasInputNode(Finding_input newHasInputNode);


    // Property http://www.pr-owl.org/pr-owl.owl#hasResidentNode

    Set<Finding_res> getHasResidentNode();

    RDFProperty getHasResidentNodeProperty();

    boolean hasHasResidentNode();

    void setHasResidentNode(Finding_res newHasResidentNode);
}
