package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Generative_input
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface Generative_input extends Input {

    // Property http://www.pr-owl.org/pr-owl.owl#isInputInstanceOf

    Object getIsInputInstanceOf();

    RDFProperty getIsInputInstanceOfProperty();

    boolean hasIsInputInstanceOf();

    void setIsInputInstanceOf(Object newIsInputInstanceOf);
}
