package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/BayesianDiagnosis.owl#HypothesisNode
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface HypothesisNode extends Node {
}
