package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Network
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Network extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasConnection

    Set getHasConnection();

    RDFProperty getHasConnectionProperty();

    boolean hasHasConnection();

    Iterator listHasConnection();

    void addHasConnection(Connection newHasConnection);

    void removeHasConnection(Connection oldHasConnection);

    void setHasConnection(Set newHasConnection);


    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasDevice

    Set getHasDevice();

    RDFProperty getHasDeviceProperty();

    boolean hasHasDevice();

    Iterator listHasDevice();

    void addHasDevice(Device newHasDevice);

    void removeHasDevice(Device oldHasDevice);

    void setHasDevice(Set newHasDevice);
}
