package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Node
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public interface Node extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#hasArgument

    Set getHasArgument();

    RDFProperty getHasArgumentProperty();

    boolean hasHasArgument();

    Iterator listHasArgument();

    void addHasArgument(ArgRelationship newHasArgument);

    void removeHasArgument(ArgRelationship oldHasArgument);

    void setHasArgument(Set newHasArgument);


    // Property http://www.pr-owl.org/pr-owl.owl#hasInnerTerm

    Set getHasInnerTerm();

    RDFProperty getHasInnerTermProperty();

    boolean hasHasInnerTerm();

    Iterator listHasInnerTerm();

    void addHasInnerTerm(Node newHasInnerTerm);

    void removeHasInnerTerm(Node oldHasInnerTerm);

    void setHasInnerTerm(Set newHasInnerTerm);


    // Property http://www.pr-owl.org/pr-owl.owl#hasPossibleValues

    Set getHasPossibleValues();

    RDFProperty getHasPossibleValuesProperty();

    boolean hasHasPossibleValues();

    Iterator listHasPossibleValues();

    void addHasPossibleValues(Entity newHasPossibleValues);

    void removeHasPossibleValues(Entity oldHasPossibleValues);

    void setHasPossibleValues(Set newHasPossibleValues);


    // Property http://www.pr-owl.org/pr-owl.owl#hasVerticalPosition

    RDFSLiteral getHasVerticalPosition();

    RDFProperty getHasVerticalPositionProperty();

    boolean hasHasVerticalPosition();

    void setHasVerticalPosition(RDFSLiteral newHasVerticalPosition);


    // Property http://www.pr-owl.org/pr-owl.owl#isInnerTermOf

    Set getIsInnerTermOf();

    RDFProperty getIsInnerTermOfProperty();

    boolean hasIsInnerTermOf();

    Iterator listIsInnerTermOf();

    void addIsInnerTermOf(Node newIsInnerTermOf);

    void removeIsInnerTermOf(Node oldIsInnerTermOf);

    void setIsInnerTermOf(Set newIsInnerTermOf);


    // Property http://www.pr-owl.org/pr-owl.owl#isNodeFrom

    Set getIsNodeFrom();

    RDFProperty getIsNodeFromProperty();

    boolean hasIsNodeFrom();

    Iterator listIsNodeFrom();

    void addIsNodeFrom(MFrag newIsNodeFrom);

    void removeIsNodeFrom(MFrag oldIsNodeFrom);

    void setIsNodeFrom(Set newIsNodeFrom);
}
