package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ProbDist
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface ProbDist extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#isDefault

    boolean getIsDefault();

    RDFProperty getIsDefaultProperty();

    boolean hasIsDefault();

    void setIsDefault(boolean newIsDefault);


    // Property http://www.pr-owl.org/pr-owl.owl#isProbDistOf

    Resident getIsProbDistOf();

    RDFProperty getIsProbDistOfProperty();

    boolean hasIsProbDistOf();

    Iterator listIsProbDistOf();

    void addIsProbDistOf(Resident newIsProbDistOf);

    void removeIsProbDistOf(Resident oldIsProbDistOf);

    void setIsProbDistOf(Set newIsProbDistOf);
}
