package es.upm.dit.gsi.ontology;
import edu.stanford.smi.protegex.owl.model.*;

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ProbAssign
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public interface ProbAssign extends OWLIndividual {

    // Property http://www.pr-owl.org/pr-owl.owl#hasConditionant

    Set getHasConditionant();

    RDFProperty getHasConditionantProperty();

    boolean hasHasConditionant();

    Iterator listHasConditionant();

    void addHasConditionant(CondRelationship newHasConditionant);

    void removeHasConditionant(CondRelationship oldHasConditionant);

    void setHasConditionant(Set newHasConditionant);


    // Property http://www.pr-owl.org/pr-owl.owl#hasStateName

    Entity getHasStateName();

    RDFProperty getHasStateNameProperty();

    boolean hasHasStateName();

    void setHasStateName(Entity newHasStateName);


    // Property http://www.pr-owl.org/pr-owl.owl#hasStateProb

    RDFSLiteral getHasStateProb();

    RDFProperty getHasStateProbProperty();

    boolean hasHasStateProb();

    void setHasStateProb(RDFSLiteral newHasStateProb);


    // Property http://www.pr-owl.org/pr-owl.owl#isProbAssignIn

    PR_OWLTable getIsProbAssignIn();

    RDFProperty getIsProbAssignInProperty();

    boolean hasIsProbAssignIn();

    void setIsProbAssignIn(PR_OWLTable newIsProbAssignIn);
}
