package es.upm.dit.gsi.ontology;

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#SimpleArgRelationship
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public interface SimpleArgRelationship extends ArgRelationship {

    // Property http://www.pr-owl.org/pr-owl.owl#hasArgTerm

    OVariable getHasArgTerm();

    RDFProperty getHasArgTermProperty();

    boolean hasHasArgTerm();

    void setHasArgTerm(OVariable newHasArgTerm);


    // Property http://www.pr-owl.org/pr-owl.owl#isArgumentOf

    Node getIsArgumentOf();

    RDFProperty getIsArgumentOfProperty();

    boolean hasIsArgumentOf();

    void setIsArgumentOf(Node newIsArgumentOf);
}
