package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.DeclarativeDist;
/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#DeclarativeDist
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public class DefaultDeclarativeDist extends DefaultProbDist
         implements DeclarativeDist {

    public DefaultDeclarativeDist(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultDeclarativeDist() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasDeclaration

    public String getHasDeclaration() {
        return (String) getPropertyValue(getHasDeclarationProperty());
    }


    public RDFProperty getHasDeclarationProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasDeclaration";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasDeclaration() {
        return getPropertyValueCount(getHasDeclarationProperty()) > 0;
    }


    public void setHasDeclaration(String newHasDeclaration) {
        setPropertyValue(getHasDeclarationProperty(), newHasDeclaration);
    }
}
