package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.Node;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Node
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultNode extends AbstractCodeGeneratorIndividual
         implements Node {

    public DefaultNode(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultNode() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasArgument

    public Set getHasArgument() {
        return new HashSet(getPropertyValuesAs(getHasArgumentProperty(), ArgRelationship.class));
    }


    public RDFProperty getHasArgumentProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasArgument";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasArgument() {
        return getPropertyValueCount(getHasArgumentProperty()) > 0;
    }


    public Iterator listHasArgument() {
        return listPropertyValuesAs(getHasArgumentProperty(), ArgRelationship.class);
    }


    public void addHasArgument(ArgRelationship newHasArgument) {
        addPropertyValue(getHasArgumentProperty(), newHasArgument);
    }


    public void removeHasArgument(ArgRelationship oldHasArgument) {
        removePropertyValue(getHasArgumentProperty(), oldHasArgument);
    }


    public void setHasArgument(Set newHasArgument) {
        setPropertyValues(getHasArgumentProperty(), newHasArgument);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasInnerTerm

    public Set getHasInnerTerm() {
        return new HashSet(getPropertyValuesAs(getHasInnerTermProperty(), Node.class));
    }


    public RDFProperty getHasInnerTermProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasInnerTerm";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasInnerTerm() {
        return getPropertyValueCount(getHasInnerTermProperty()) > 0;
    }


    public Iterator listHasInnerTerm() {
        return listPropertyValuesAs(getHasInnerTermProperty(), Node.class);
    }


    public void addHasInnerTerm(Node newHasInnerTerm) {
        addPropertyValue(getHasInnerTermProperty(), newHasInnerTerm);
    }


    public void removeHasInnerTerm(Node oldHasInnerTerm) {
        removePropertyValue(getHasInnerTermProperty(), oldHasInnerTerm);
    }


    public void setHasInnerTerm(Set newHasInnerTerm) {
        setPropertyValues(getHasInnerTermProperty(), newHasInnerTerm);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasPossibleValues

    public Set getHasPossibleValues() {
        return new HashSet(getPropertyValuesAs(getHasPossibleValuesProperty(), Entity.class));
    }


    public RDFProperty getHasPossibleValuesProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasPossibleValues";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasPossibleValues() {
        return getPropertyValueCount(getHasPossibleValuesProperty()) > 0;
    }


    public Iterator listHasPossibleValues() {
        return listPropertyValuesAs(getHasPossibleValuesProperty(), Entity.class);
    }


    public void addHasPossibleValues(Entity newHasPossibleValues) {
        addPropertyValue(getHasPossibleValuesProperty(), newHasPossibleValues);
    }


    public void removeHasPossibleValues(Entity oldHasPossibleValues) {
        removePropertyValue(getHasPossibleValuesProperty(), oldHasPossibleValues);
    }


    public void setHasPossibleValues(Set newHasPossibleValues) {
        setPropertyValues(getHasPossibleValuesProperty(), newHasPossibleValues);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasVerticalPosition

    public RDFSLiteral getHasVerticalPosition() {
        return (RDFSLiteral) getPropertyValue(getHasVerticalPositionProperty());
    }


    public RDFProperty getHasVerticalPositionProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasVerticalPosition";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasVerticalPosition() {
        return getPropertyValueCount(getHasVerticalPositionProperty()) > 0;
    }


    public void setHasVerticalPosition(RDFSLiteral newHasVerticalPosition) {
        setPropertyValue(getHasVerticalPositionProperty(), newHasVerticalPosition);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isInnerTermOf

    public Set getIsInnerTermOf() {
        return new HashSet(getPropertyValuesAs(getIsInnerTermOfProperty(), Node.class));
    }


    public RDFProperty getIsInnerTermOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isInnerTermOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsInnerTermOf() {
        return getPropertyValueCount(getIsInnerTermOfProperty()) > 0;
    }


    public Iterator listIsInnerTermOf() {
        return listPropertyValuesAs(getIsInnerTermOfProperty(), Node.class);
    }


    public void addIsInnerTermOf(Node newIsInnerTermOf) {
        addPropertyValue(getIsInnerTermOfProperty(), newIsInnerTermOf);
    }


    public void removeIsInnerTermOf(Node oldIsInnerTermOf) {
        removePropertyValue(getIsInnerTermOfProperty(), oldIsInnerTermOf);
    }


    public void setIsInnerTermOf(Set newIsInnerTermOf) {
        setPropertyValues(getIsInnerTermOfProperty(), newIsInnerTermOf);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isNodeFrom

    public Set getIsNodeFrom() {
        return new HashSet(getPropertyValuesAs(getIsNodeFromProperty(), MFrag.class));
    }


    public RDFProperty getIsNodeFromProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isNodeFrom";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsNodeFrom() {
        return getPropertyValueCount(getIsNodeFromProperty()) > 0;
    }


    public Iterator listIsNodeFrom() {
        return listPropertyValuesAs(getIsNodeFromProperty(), MFrag.class);
    }


    public void addIsNodeFrom(MFrag newIsNodeFrom) {
        addPropertyValue(getIsNodeFromProperty(), newIsNodeFrom);
    }


    public void removeIsNodeFrom(MFrag oldIsNodeFrom) {
        removePropertyValue(getIsNodeFromProperty(), oldIsNodeFrom);
    }


    public void setIsNodeFrom(Set newIsNodeFrom) {
        setPropertyValues(getIsNodeFromProperty(), newIsNodeFrom);
    }
}
