package es.upm.dit.gsi.ontology.impl;

import java.util.Set;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#DeclarativeDist
 *
 * @version generated on Fri Apr 01 15:09:42 CEST 2011
 */
public class DefaultDeclarativeDist extends DefaultProbDist
         implements DeclarativeDist {

    public DefaultDeclarativeDist(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultDeclarativeDist() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasDeclaration

    public String getHasDeclaration() {
        return (String) getPropertyValue(getHasDeclarationProperty());
    }


    public RDFProperty getHasDeclarationProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasDeclaration";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasDeclaration() {
        return getPropertyValueCount(getHasDeclarationProperty()) > 0;
    }


    public void setHasDeclaration(String newHasDeclaration) {
        setPropertyValue(getHasDeclarationProperty(), newHasDeclaration);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isProbDistOf
//
//    public Resident getIsProbDistOf() {
//        return (Resident) getPropertyValueAs(getIsProbDistOfProperty(), Resident.class);
//    }

    public Resident getIsProbDistOf() {
        return (Resident) getPropertyValueAs(getIsProbDistOfProperty(), Resident.class);
    }



    public RDFProperty getIsProbDistOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isProbDistOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsProbDistOf() {
        return getPropertyValueCount(getIsProbDistOfProperty()) > 0;
    }


    public void setIsProbDistOf(Resident newIsProbDistOf) {
        setPropertyValue(getIsProbDistOfProperty(), newIsProbDistOf);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isRepresentedAs

    public Object getIsRepresentedAs() {
        return (Object) getPropertyValue(getIsRepresentedAsProperty());
    }


    public RDFProperty getIsRepresentedAsProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isRepresentedAs";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsRepresentedAs() {
        return getPropertyValueCount(getIsRepresentedAsProperty()) > 0;
    }


    public void setIsRepresentedAs(Object newIsRepresentedAs) {
        setPropertyValue(getIsRepresentedAsProperty(), newIsRepresentedAs);
    }
}
