package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import java.util.*;

import es.upm.dit.gsi.ontology.*;
import es.upm.dit.gsi.ontology.System;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Diagnosis.owl#Symptom
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultSymptom extends AbstractCodeGeneratorIndividual
         implements Symptom {

    public DefaultSymptom(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultSymptom() {
    }



    // Property http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation

    public Set getHasBayesianObservation() {
        return new HashSet(getPropertyValuesAs(getHasBayesianObservationProperty(), ObservationNode.class));
    }


    public RDFProperty getHasBayesianObservationProperty() {
        final String uri = "http://www.owl-ontologies.com/BayesianDiagnosis.owl#hasBayesianObservation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasBayesianObservation() {
        return getPropertyValueCount(getHasBayesianObservationProperty()) > 0;
    }


    public Iterator listHasBayesianObservation() {
        return listPropertyValuesAs(getHasBayesianObservationProperty(), ObservationNode.class);
    }


    public void addHasBayesianObservation(ObservationNode newHasBayesianObservation) {
        addPropertyValue(getHasBayesianObservationProperty(), newHasBayesianObservation);
    }


    public void removeHasBayesianObservation(ObservationNode oldHasBayesianObservation) {
        removePropertyValue(getHasBayesianObservationProperty(), oldHasBayesianObservation);
    }


    public void setHasBayesianObservation(Set newHasBayesianObservation) {
        setPropertyValues(getHasBayesianObservationProperty(), newHasBayesianObservation);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#hasLocation

    public System getHasLocation() {
        return (System) getPropertyValueAs(getHasLocationProperty(), System.class);
    }


    public RDFProperty getHasLocationProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#hasLocation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasLocation() {
        return getPropertyValueCount(getHasLocationProperty()) > 0;
    }


    public void setHasLocation(System newHasLocation) {
        setPropertyValue(getHasLocationProperty(), newHasLocation);
    }



    // Property http://www.owl-ontologies.com/Diagnosis.owl#startsDiagnosis

    public Set getStartsDiagnosis() {
        return new HashSet(getPropertyValuesAs(getStartsDiagnosisProperty(), Diagnosis.class));
    }


    public RDFProperty getStartsDiagnosisProperty() {
        final String uri = "http://www.owl-ontologies.com/Diagnosis.owl#startsDiagnosis";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasStartsDiagnosis() {
        return getPropertyValueCount(getStartsDiagnosisProperty()) > 0;
    }


    public Iterator listStartsDiagnosis() {
        return listPropertyValuesAs(getStartsDiagnosisProperty(), Diagnosis.class);
    }


    public void addStartsDiagnosis(Diagnosis newStartsDiagnosis) {
        addPropertyValue(getStartsDiagnosisProperty(), newStartsDiagnosis);
    }


    public void removeStartsDiagnosis(Diagnosis oldStartsDiagnosis) {
        removePropertyValue(getStartsDiagnosisProperty(), oldStartsDiagnosis);
    }


    public void setStartsDiagnosis(Set newStartsDiagnosis) {
        setPropertyValues(getStartsDiagnosisProperty(), newStartsDiagnosis);
    }
}
