package es.upm.dit.gsi.ontology.impl;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.BooleanRVState;
import es.upm.dit.gsi.ontology.BuiltInRV;
import es.upm.dit.gsi.ontology.Context;
import es.upm.dit.gsi.ontology.Input;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#BuiltInRV
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public class DefaultBuiltInRV extends AbstractCodeGeneratorIndividual
         implements BuiltInRV {

    public DefaultBuiltInRV(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultBuiltInRV() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasContextInstance

    public Set getHasContextInstance() {
        return new HashSet(getPropertyValuesAs(getHasContextInstanceProperty(), Context.class));
    }


    public RDFProperty getHasContextInstanceProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasContextInstance";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasContextInstance() {
        return getPropertyValueCount(getHasContextInstanceProperty()) > 0;
    }


    public Iterator listHasContextInstance() {
        return listPropertyValuesAs(getHasContextInstanceProperty(), Context.class);
    }


    public void addHasContextInstance(Context newHasContextInstance) {
        addPropertyValue(getHasContextInstanceProperty(), newHasContextInstance);
    }


    public void removeHasContextInstance(Context oldHasContextInstance) {
        removePropertyValue(getHasContextInstanceProperty(), oldHasContextInstance);
    }


    public void setHasContextInstance(Set newHasContextInstance) {
        setPropertyValues(getHasContextInstanceProperty(), newHasContextInstance);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasInputInstance

    public Set getHasInputInstance() {
        return new HashSet(getPropertyValuesAs(getHasInputInstanceProperty(), Input.class));
    }


    public RDFProperty getHasInputInstanceProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasInputInstance";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasInputInstance() {
        return getPropertyValueCount(getHasInputInstanceProperty()) > 0;
    }


    public Iterator listHasInputInstance() {
        return listPropertyValuesAs(getHasInputInstanceProperty(), Input.class);
    }


    public void addHasInputInstance(Input newHasInputInstance) {
        addPropertyValue(getHasInputInstanceProperty(), newHasInputInstance);
    }


    public void removeHasInputInstance(Input oldHasInputInstance) {
        removePropertyValue(getHasInputInstanceProperty(), oldHasInputInstance);
    }


    public void setHasInputInstance(Set newHasInputInstance) {
        setPropertyValues(getHasInputInstanceProperty(), newHasInputInstance);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasPossibleValues

    public Set getHasPossibleValues() {
        return new HashSet(getPropertyValuesAs(getHasPossibleValuesProperty(), BooleanRVState.class));
    }


    public RDFProperty getHasPossibleValuesProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasPossibleValues";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasPossibleValues() {
        return getPropertyValueCount(getHasPossibleValuesProperty()) > 0;
    }


    public Iterator listHasPossibleValues() {
        return listPropertyValuesAs(getHasPossibleValuesProperty(), BooleanRVState.class);
    }


    public void addHasPossibleValues(BooleanRVState newHasPossibleValues) {
        addPropertyValue(getHasPossibleValuesProperty(), newHasPossibleValues);
    }


    public void removeHasPossibleValues(BooleanRVState oldHasPossibleValues) {
        removePropertyValue(getHasPossibleValuesProperty(), oldHasPossibleValues);
    }


    public void setHasPossibleValues(Set newHasPossibleValues) {
        setPropertyValues(getHasPossibleValuesProperty(), newHasPossibleValues);
    }
}
