package es.upm.dit.gsi.ontology.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import es.upm.dit.gsi.ontology.ArgRelationship;
import es.upm.dit.gsi.ontology.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ArgRelationship
 *
 * @version generated on Fri Apr 01 15:09:41 CEST 2011
 */
public class DefaultArgRelationship extends AbstractCodeGeneratorIndividual
         implements ArgRelationship {

    public DefaultArgRelationship(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultArgRelationship() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasArgNumber

    public RDFSLiteral getHasArgNumber() {
        return (RDFSLiteral) getPropertyValue(getHasArgNumberProperty());
    }


    public RDFProperty getHasArgNumberProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasArgNumber";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasArgNumber() {
        return getPropertyValueCount(getHasArgNumberProperty()) > 0;
    }


    public void setHasArgNumber(RDFSLiteral newHasArgNumber) {
        setPropertyValue(getHasArgNumberProperty(), newHasArgNumber);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasArgTerm

    public Object getHasArgTerm() {
        return (Object) getPropertyValue(getHasArgTermProperty());
    }


    public RDFProperty getHasArgTermProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasArgTerm";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasArgTerm() {
        return getPropertyValueCount(getHasArgTermProperty()) > 0;
    }


    public void setHasArgTerm(Object newHasArgTerm) {
        setPropertyValue(getHasArgTermProperty(), newHasArgTerm);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isArgumentOf

    public Node getIsArgumentOf() {
        return (Node) getPropertyValueAs(getIsArgumentOfProperty(), Node.class);
    }


    public RDFProperty getIsArgumentOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isArgumentOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsArgumentOf() {
        return getPropertyValueCount(getIsArgumentOfProperty()) > 0;
    }


    public void setIsArgumentOf(Node newIsArgumentOf) {
        setPropertyValue(getIsArgumentOfProperty(), newIsArgumentOf);
    }
}
