package es.upm.dit.gsi.ontology.impl;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.OVariable;
import es.upm.dit.gsi.ontology.ObjectEntity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#ObjectEntity
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public class DefaultObjectEntity extends DefaultEntity
         implements ObjectEntity {

    public DefaultObjectEntity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultObjectEntity() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#subsOVar

    public Set getSubsOVar() {
        return new HashSet(getPropertyValuesAs(getSubsOVarProperty(), OVariable.class));
    }


    public RDFProperty getSubsOVarProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#subsOVar";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasSubsOVar() {
        return getPropertyValueCount(getSubsOVarProperty()) > 0;
    }


    public Iterator listSubsOVar() {
        return listPropertyValuesAs(getSubsOVarProperty(), OVariable.class);
    }


    public void addSubsOVar(OVariable newSubsOVar) {
        addPropertyValue(getSubsOVarProperty(), newSubsOVar);
    }


    public void removeSubsOVar(OVariable oldSubsOVar) {
        removePropertyValue(getSubsOVarProperty(), oldSubsOVar);
    }


    public void setSubsOVar(Set newSubsOVar) {
        setPropertyValues(getSubsOVarProperty(), newSubsOVar);
    }
}
