package es.upm.dit.gsi.ontology.impl;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import es.upm.dit.gsi.ontology.Context;
import es.upm.dit.gsi.ontology.Domain_MFrag;
import es.upm.dit.gsi.ontology.Entity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.pr-owl.org/pr-owl.owl#Context
 *
 * @version generated on Mon Jun 27 12:29:14 CEST 2011
 */
public class DefaultContext extends DefaultNode
         implements Context {

    public DefaultContext(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultContext() {
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasInnerTerm

    public Set getHasInnerTerm() {
        return new HashSet(getPropertyValuesAs(getHasInnerTermProperty(), Context.class));
    }


    public RDFProperty getHasInnerTermProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasInnerTerm";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasInnerTerm() {
        return getPropertyValueCount(getHasInnerTermProperty()) > 0;
    }


    public Iterator listHasInnerTerm() {
        return listPropertyValuesAs(getHasInnerTermProperty(), Context.class);
    }


    public void addHasInnerTerm(Context newHasInnerTerm) {
        addPropertyValue(getHasInnerTermProperty(), newHasInnerTerm);
    }


    public void removeHasInnerTerm(Context oldHasInnerTerm) {
        removePropertyValue(getHasInnerTermProperty(), oldHasInnerTerm);
    }


    public void setHasInnerTerm(Set newHasInnerTerm) {
        setPropertyValues(getHasInnerTermProperty(), newHasInnerTerm);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#hasPossibleValues

    public Set getHasPossibleValues() {
        return new HashSet(getPropertyValuesAs(getHasPossibleValuesProperty(), Entity.class));
    }


    public RDFProperty getHasPossibleValuesProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#hasPossibleValues";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasPossibleValues() {
        return getPropertyValueCount(getHasPossibleValuesProperty()) > 0;
    }


    public Iterator listHasPossibleValues() {
        return listPropertyValuesAs(getHasPossibleValuesProperty(), Entity.class);
    }


    public void addHasPossibleValues(Entity newHasPossibleValues) {
        addPropertyValue(getHasPossibleValuesProperty(), newHasPossibleValues);
    }


    public void removeHasPossibleValues(Entity oldHasPossibleValues) {
        removePropertyValue(getHasPossibleValuesProperty(), oldHasPossibleValues);
    }


    public void setHasPossibleValues(Set newHasPossibleValues) {
        setPropertyValues(getHasPossibleValuesProperty(), newHasPossibleValues);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isContextInstanceOf

    public Object getIsContextInstanceOf() {
        return (Object) getPropertyValue(getIsContextInstanceOfProperty());
    }


    public RDFProperty getIsContextInstanceOfProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isContextInstanceOf";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsContextInstanceOf() {
        return getPropertyValueCount(getIsContextInstanceOfProperty()) > 0;
    }


    public void setIsContextInstanceOf(Object newIsContextInstanceOf) {
        setPropertyValue(getIsContextInstanceOfProperty(), newIsContextInstanceOf);
    }



    // Property http://www.pr-owl.org/pr-owl.owl#isContextNodeIn

    public Set getIsContextNodeIn() {
        return new HashSet(getPropertyValuesAs(getIsContextNodeInProperty(), Domain_MFrag.class));
    }


    public RDFProperty getIsContextNodeInProperty() {
        final String uri = "http://www.pr-owl.org/pr-owl.owl#isContextNodeIn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsContextNodeIn() {
        return getPropertyValueCount(getIsContextNodeInProperty()) > 0;
    }


    public Iterator listIsContextNodeIn() {
        return listPropertyValuesAs(getIsContextNodeInProperty(), Domain_MFrag.class);
    }


    public void addIsContextNodeIn(Domain_MFrag newIsContextNodeIn) {
        addPropertyValue(getIsContextNodeInProperty(), newIsContextNodeIn);
    }


    public void removeIsContextNodeIn(Domain_MFrag oldIsContextNodeIn) {
        removePropertyValue(getIsContextNodeInProperty(), oldIsContextNodeIn);
    }


    public void setIsContextNodeIn(Set newIsContextNodeIn) {
        setPropertyValues(getIsContextNodeInProperty(), newIsContextNodeIn);
    }
}
